# Generated by Django 5.1.5 on 2025-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(blank=True, max_length=150, null=True)),
                ('access_token', models.CharField(blank=True, max_length=150, null=True)),
                ('expires_in', models.DateTimeField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
