# Generated by Django 5.1.5 on 2025-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('host', models.CharField(max_length=100, unique=True)),
                ('guest', models.BooleanField(default=True)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
