# Generated by Django 5.1.5 on 2025-01-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest',
            new_name='guest_can_pause',
        ),
    ]
