# Generated by Django 5.1.5 on 2025-01-29 09:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_guest_room_guest_can_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, default=api.models.generate_unique_code, max_length=10),
        ),
    ]
